### 주문 생성
POST http://localhost:8080/v1/orders
Content-Type: application/json

{
  "customerId": 4,
  "orderItems": [
    {
      "productId": "1743476533111_e0e7e301-195e-414c-bb2a-3244594aabfb",
      "quantity": 4
    }
  ],
  "paymentMethod": "CREDIT_CARD"
}

### 결제 처리 성공
POST http://localhost:8080/v1/orders/4/payment
Content-Type: application/json

{
  "success": true
}

### 결제 처리 실패
POST http://localhost:8080/v1/orders/2/payment
Content-Type: application/json

{
  "success": false
}

### 주문 완료
POST http://localhost:8080/v1/orders/3/complete
Content-Type: application/json

### 주문 취소
POST http://localhost:8080/v1/orders/4/cancel
Content-Type: application/json